float64 x
float64 y
float64 z
float64 thx
float64 thy
float64 thz
float64 x_vel
float64 y_vel
float64 z_vel
float64 thx_vel
float64 thy_vel
float64 thz_vel
---
float64 x_way
float64 y_way
float64 z_way
float64 thx_way
float64 thy_way
float64 thz_way